# Generated by Django 5.2.4 on 2025-07-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, help_text='The URL link to the resource', max_length=2000, null=True),
        ),
    ]
